### ISSUE TITLE
HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by saurya3d** [techwithtim/Music-Controller-Web-App-Tutorial#12]
![Untitled](https://user-images.githubusercontent.com/71386739/106009576-7bbe3000-60de-11eb-84a3-636b75f63b02.png)
tutorial 5 for create-room
"detail": "Method \"GET\" not allowed."

what should i do to resolve this error?

**Comment by yuzi-zly** [comment]
I want to know how you solve this problem
